# Data Generation Configuration for AutoOpticalDiagnostics
# This file configures the synthetic data generation process

data_generation:
  # Dataset parameters
  num_train_samples: 5000
  num_val_samples: 1000
  image_size: [512, 512]
  random_seed: 42
  
  # LSCI parameters
  lsci_wavelength: 785.0
  lsci_coherence_length: 50.0
  lsci_speckle_size: 2.0
  lsci_contrast_range: [0.1, 0.8]
  
  # OCT parameters
  oct_center_wavelength: 1300.0
  oct_bandwidth: 100.0
  oct_axial_resolution: 5.0
  oct_lateral_resolution: 10.0
  oct_depth_range: 2000.0
  
  # Defect parameters
  defect_probability: 0.3
  defect_size_range: [0.05, 0.2]
  defect_intensity_range: [0.2, 0.8]
  
  # Noise parameters
  thermal_noise_std: 0.05
  motion_blur_probability: 0.1
  motion_blur_kernel_size: 15
  gaussian_noise_std: 0.02
  salt_pepper_probability: 0.01
  quantization_noise_std: 0.01
  shot_noise_std: 0.03
  dark_current_noise_std: 0.02
  readout_noise_std: 0.01
  banding_noise_std: 0.02
  uneven_illumination_std: 0.1
  optical_distortion_probability: 0.05
  vibration_noise_std: 0.03
  humidity_noise_std: 0.02
  temperature_dependent_noise_std: 0.01